cmake_minimum_required(VERSION 2.8)


if(CMAKE_BUILD_TYPE MATCHES DEBUG)
  set(FLAG_OPTS  -O0)
  set(FLAG_DEBUG -g)
  set(PREP_DEBUG -DDEBUG)
else()
  set(FLAG_OPTS -O3)
endif(CMAKE_BUILD_TYPE MATCHES DEBUG)
set(FLAG_OPTS ${FLAG_OPTS} -mno-mmx -mno-sse -mno-sse4.2 -mno-avx)

if(REPORT_CYCLES)
  set(PREP_CYCLES -DCYCLES)
endif(REPORT_CYCLES)

if(REPORT_CHECKSUM)
  set(PREP_CHECKSUM -DCHECKSUM)
endif(REPORT_CHECKSUM)



